
import streamlit as st
import sqlite3
import pandas as pd

# Connect to the DB on your Drive
DB_PATH = 'CFIE_Master_State.db' # Streamlit will look for this

st.title("🏏 CFIE Mobile Dashboard")

# 1. SHOW LATEST FORECAST
st.header("Latest Forecast Contract")
try:
    conn = sqlite3.connect(DB_PATH)
    # We fetch the latest forecast generated by Step 3/5
    query = "SELECT * FROM post_match_logs ORDER BY processed_at DESC LIMIT 1"
    df = pd.read_sql(query, conn)
    if not df.empty:
        st.write(df)
        
        # 13.0 ABSTENTION ALERT
        prob = df['calibrated_probability'].iloc[0]
        if 0.43 <= prob <= 0.57:
            st.error("🚫 ABSTAIN: Probability in Dead Zone (43%-57%)")
        else:
            st.success("✅ TRADE SIGNAL ACTIVE")
    else:
        st.info("No forecasts generated yet.")
    conn.close()
except Exception as e:
    st.error(f"Waiting for database... {e}")

# 2. SHOW CALIBRATION HEALTH
st.header("System Health (Rule 15.0)")
try:
    conn = sqlite3.connect(DB_PATH)
    health_query = "SELECT league, AVG(brier_score) as avg_brier FROM post_match_logs GROUP BY league"
    health_df = pd.read_sql(health_query, conn)
    st.bar_chart(health_df.set_index('league'))
    conn.close()
except:
    pass
